optimizer: adam
regularization: l2
alpha: 0.0025
batch_size: 4096
lr: 1.0e-3
steps: 1000
log_steps: 100
n_support: 128
source:
  setting: continuous
  mean: 1.0
  std: 0.35
  support: [-2, 4]
  n_samples: None
target:
  setting: continuous
  mean: -1.0
  std: 0.15
  support: [-4, 2]
  n_samples: None